name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download deps
        run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
        shell: bash
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - name: Build
        run: |
          git clone https://github.com/MoAlyousef/cfltk --recurse-submodules
          cd cfltk
          ./scripts/bootstrap_linux.sh
          cd ../
          zig build
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - name: Build
        run: |
          git clone https://github.com/MoAlyousef/cfltk --recurse-submodules
          cd cfltk
          ./scripts/bootstrap_macos.sh
          cd ../
          zig build
  build_windows-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - shell: msys2 {0}
        run: |
          pacman -Sy
          pacman --noconfirm -S $MINGW_PACKAGE_PREFIX-cmake $MINGW_PACKAGE_PREFIX-ninja $MINGW_PACKAGE_PREFIX-cc wget unzip git --needed
          wget https://ziglang.org/download/0.10.0/zig-windows-x86_64-0.10.0.zip
          unzip zig-windows-x86_64-0.10.0.zip
          git clone https://github.com/MoAlyousef/cfltk --recurse-submodules
          cd cfltk
          ./scripts/bootstrap_windows.sh
          cd ..
          zig-windows-x86_64-0.10.0/zig build --search-prefix $MINGW_PREFIX
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - name: build
        run: |
          git clone https://github.com/MoAlyousef/cfltk --recurse-submodules
          cd cfltk
          cmake -Bbin -DOPTION_USE_SYSTEM_LIBPNG=OFF -DOPTION_USE_SYSTEM_LIBJPEG=OFF -DOPTION_USE_SYSTEM_ZLIB=OFF -DCFLTK_LINK_IMAGES=ON -DOPTION_USE_GL=OFF -DCFLTK_USE_OPENGL=OFF -DCFLTK_SINGLE_THREADED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_BUILD_TEST=OFF -DOPTION_LARGE_FILE=ON -DOPTION_USE_THREADS=ON -DOPTION_BUILD_HTML_DOCUMENTATION=OFF -DOPTION_BUILD_PDF_DOCUMENTATION=OFF -DCMAKE_INSTALL_PREFIX=C:\cfltk -DCMAKE_BUILD_TYPE=Release
          cmake --build bin --parallel --target install 
          cd ..
          zig build --search-prefix C:\cfltk
